CREATE TABLE IF NOT EXISTS token (
    id INT AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL,
    inisial VARCHAR(255),
    fid VARCHAR(255),
    token VARCHAR(255),
    dibuat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    diedit TIMESTAMP,
    dihapus TIMESTAMP,
    INDEX (uuid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
