CREATE TABLE IF NOT EXISTS sample (
    id INT AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL,
    nama VARCHAR(255),
    tech VARCHAR(255),
    dibuat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    diedit TIMESTAMP,
    dihapus TIMESTAMP,
    INDEX (uuid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
