CREATE TABLE IF NOT EXISTS log (
    id INT AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL,
    email VARCHAR(255),
    device TEXT,
    lokasi VARCHAR(255),
    ip VARCHAR(255),
    aktifitas LONGTEXT,
    inisial VARCHAR(255),
    dibuat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    diedit TIMESTAMP,
    dihapus TIMESTAMP,
    INDEX (uuid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
